name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: dropdown
  attributes:
    label: Related Areas
    description: Which of these areas in the game is affected by the issue? Select all that apply
    multiple: true
    options:
      - The minimap
      - The world map
      - Quest tracker
      - Quest log menu
      - PFQ journal
      - PFQ config
      - PFQ routes
      - PFQ routes arrow
      - PFQ quest markers
      - PFQ `/db` command
      - Quest chat links
- type: textarea
  id: logs
  attributes:
    label: Lua Error Logs
    description: If you receive a `Lua Error` popup, you can select all text and paste here.
    render: shell
  validations:
    required: false
- type: textarea
  attributes:
    label: Screenshots or Other Information
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false